"""Kuwait market vehicle makes & models seed data."""

KUWAIT_MAKES_MODELS = [
    {"label": "Toyota", "models": ["Camry", "Corolla", "Land Cruiser", "Prado", "RAV4", "Yaris", "Hilux", "Fortuner", "Hiace", "Avalon", "Rush", "Innova"]},
    {"label": "Lexus", "models": ["LX 600", "LX 570", "GX 460", "RX 350", "ES 350", "LS 500", "IS 350", "NX 300", "UX 200", "LC 500"]},
    {"label": "Nissan", "models": ["Patrol", "Altima", "Sentra", "Maxima", "X-Trail", "Sunny", "Pathfinder", "Navara", "Kicks", "Murano", "Patrol Pickup"]},
    {"label": "Mitsubishi", "models": ["Pajero", "Outlander", "Lancer", "ASX", "L200", "Mirage", "Attrage", "Eclipse Cross", "Montero Sport"]},
    {"label": "Land Rover", "models": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Defender", "Discovery", "Discovery Sport"]},
    {"label": "BMW", "models": ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6", "X7", "M4", "M5", "i7", "iX"]},
    {"label": "Mercedes-Benz", "models": ["C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "GLS", "G-Class", "A-Class", "AMG GT", "EQS", "Maybach"]},
    {"label": "Chevrolet", "models": ["Tahoe", "Suburban", "Silverado", "Camaro", "Corvette", "Captiva", "Malibu", "Traverse", "Impala", "Trailblazer"]},
    {"label": "GMC", "models": ["Yukon", "Yukon Denali", "Sierra", "Acadia", "Terrain", "Canyon"]},
    {"label": "Ford", "models": ["F-150", "Mustang", "Explorer", "Edge", "Expedition", "Escape", "Ranger", "Bronco", "Territory"]},
    {"label": "Hyundai", "models": ["Sonata", "Elantra", "Tucson", "Santa Fe", "Accent", "Creta", "Palisade", "Kona", "i10", "i20", "Staria"]},
    {"label": "Kia", "models": ["Sportage", "Sorento", "Cerato", "Optima", "Picanto", "Rio", "Telluride", "Carnival", "Stinger", "Seltos", "EV6"]},
    {"label": "Honda", "models": ["Accord", "Civic", "CR-V", "Pilot", "HR-V", "Odyssey", "City"]},
    {"label": "Mazda", "models": ["CX-5", "CX-9", "CX-3", "CX-30", "Mazda3", "Mazda6", "MX-5"]},
    {"label": "Infiniti", "models": ["QX80", "QX60", "QX50", "Q50", "Q60", "QX55"]},
    {"label": "Jeep", "models": ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade", "Gladiator", "Wagoneer"]},
    {"label": "Dodge", "models": ["Charger", "Challenger", "Durango", "Ram 1500", "Ram 2500"]},
    {"label": "Porsche", "models": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Cayman", "Boxster"]},
    {"label": "Audi", "models": ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "RS Q8", "e-tron"]},
    {"label": "Volkswagen", "models": ["Tiguan", "Touareg", "Passat", "Jetta", "Golf", "Teramont", "T-Roc"]},
    {"label": "Tesla", "models": ["Model S", "Model 3", "Model X", "Model Y"]},
    {"label": "Cadillac", "models": ["Escalade", "XT5", "XT6", "CT5", "CT4", "Lyriq"]},
    {"label": "Suzuki", "models": ["Swift", "Vitara", "Jimny", "Baleno", "Ciaz", "Dzire", "Grand Vitara"]},
    {"label": "Volvo", "models": ["XC40", "XC60", "XC90", "S60", "S90"]},
    {"label": "Peugeot", "models": ["208", "301", "508", "2008", "3008", "5008"]},
    {"label": "MG", "models": ["MG5", "MG6", "ZS", "RX5", "HS", "Gloster", "Marvel R"]},
    {"label": "Geely", "models": ["Emgrand", "Coolray", "Tugella", "Atlas", "Boyue", "Monjaro"]},
    {"label": "Chery", "models": ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 6"]},
    {"label": "Bentley", "models": ["Bentayga", "Continental GT", "Flying Spur"]},
    {"label": "Rolls-Royce", "models": ["Phantom", "Ghost", "Cullinan", "Wraith", "Dawn", "Spectre"]},
]
